CREATE TYPE "ProductCategory" AS ENUM ('MAIN','ADDITIONAL');
CREATE TYPE "OrderStatus" AS ENUM ('NEW','AWAITING_PAYMENT','PAID','PROCESSING','READY_TO_SHIP','SHIPPED','COMPLETED','CANCELLED','REFUNDED');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING','SUCCEEDED','FAILED','CANCELLED','REFUNDED');
CREATE TYPE "DeliveryMethod" AS ENUM ('CDEK');
CREATE TYPE "DeliveryType" AS ENUM ('PICKUP','COURIER');
CREATE TYPE "ShashkaSize" AS ENUM ('ADULT','TEEN','CHILD','BY_HEIGHT');
CREATE TYPE "ContentKind" AS ENUM ('TEXT','RICH_TEXT','IMAGE','VIDEO','JSON');

CREATE TABLE "AdminUser" ("id" TEXT NOT NULL,"email" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"name" TEXT,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "AdminUser_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Product" ("id" TEXT NOT NULL,"slug" TEXT NOT NULL,"category" "ProductCategory" NOT NULL,"name" TEXT NOT NULL,"subtitle" TEXT,"description" TEXT NOT NULL,"price" DECIMAL(12,2) NOT NULL,"oldPrice" DECIMAL(12,2),"composition" TEXT[],"benefits" TEXT[],"imageUrl" TEXT,"badge" TEXT,"buttonLabel" TEXT NOT NULL DEFAULT 'Купить комплект',"weightGrams" INTEGER NOT NULL DEFAULT 1000,"lengthCm" INTEGER NOT NULL DEFAULT 30,"widthCm" INTEGER NOT NULL DEFAULT 20,"heightCm" INTEGER NOT NULL DEFAULT 10,"packageCount" INTEGER NOT NULL DEFAULT 1,"sortOrder" INTEGER NOT NULL DEFAULT 0,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Product_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Review" ("id" TEXT NOT NULL,"authorName" TEXT NOT NULL,"city" TEXT,"text" TEXT NOT NULL,"rating" INTEGER NOT NULL,"imageUrl" TEXT,"reviewDate" TIMESTAMP(3),"showOnHomepage" BOOLEAN NOT NULL DEFAULT false,"isVisible" BOOLEAN NOT NULL DEFAULT true,"sortOrder" INTEGER NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Review_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FaqItem" ("id" TEXT NOT NULL,"question" TEXT NOT NULL,"answer" TEXT NOT NULL,"sortOrder" INTEGER NOT NULL DEFAULT 0,"isVisible" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "FaqItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ContentBlock" ("id" TEXT NOT NULL,"key" TEXT NOT NULL,"section" TEXT NOT NULL,"label" TEXT NOT NULL,"kind" "ContentKind" NOT NULL DEFAULT 'TEXT',"value" JSONB NOT NULL,"sortOrder" INTEGER NOT NULL DEFAULT 0,"isVisible" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ContentBlock_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SiteSetting" ("id" TEXT NOT NULL,"key" TEXT NOT NULL,"label" TEXT NOT NULL,"value" JSONB NOT NULL,"isSecret" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "SiteSetting_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Media" ("id" TEXT NOT NULL,"originalName" TEXT NOT NULL,"fileName" TEXT NOT NULL,"mimeType" TEXT NOT NULL,"size" INTEGER NOT NULL,"path" TEXT NOT NULL,"alt" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Media_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Order" ("id" TEXT NOT NULL,"number" TEXT NOT NULL,"status" "OrderStatus" NOT NULL DEFAULT 'NEW',"customerName" TEXT NOT NULL,"phone" TEXT NOT NULL,"email" TEXT NOT NULL,"city" TEXT NOT NULL,"postalCode" TEXT,"deliveryMethod" "DeliveryMethod" NOT NULL,"deliveryType" "DeliveryType" NOT NULL,"deliveryAddress" TEXT,"cdekCityCode" INTEGER NOT NULL,"cdekPointCode" TEXT,"cdekPointName" TEXT,"cdekPointAddress" TEXT,"cdekTariffCode" INTEGER NOT NULL,"cdekTariffName" TEXT NOT NULL,"deliveryMinDays" INTEGER,"deliveryMaxDays" INTEGER,"deliveryQuoteId" TEXT NOT NULL,"deliveryQuotedAt" TIMESTAMP(3) NOT NULL,"cdekOrderUuid" TEXT,"cdekNumber" TEXT,"shashkaSize" "ShashkaSize" NOT NULL,"customerHeight" INTEGER,"customerComment" TEXT,"adminNote" TEXT,"subtotal" DECIMAL(12,2) NOT NULL,"deliveryPrice" DECIMAL(12,2) NOT NULL DEFAULT 0,"total" DECIMAL(12,2) NOT NULL,"utm" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Order_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OrderItem" ("id" TEXT NOT NULL,"orderId" TEXT NOT NULL,"productId" TEXT,"productName" TEXT NOT NULL,"productSlug" TEXT NOT NULL,"unitPrice" DECIMAL(12,2) NOT NULL,"quantity" INTEGER NOT NULL,"total" DECIMAL(12,2) NOT NULL,CONSTRAINT "OrderItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Payment" ("id" TEXT NOT NULL,"orderId" TEXT NOT NULL,"provider" TEXT NOT NULL,"providerPaymentId" TEXT,"invoiceId" INTEGER NOT NULL,"idempotencyKey" TEXT NOT NULL,"status" "PaymentStatus" NOT NULL DEFAULT 'PENDING',"amount" DECIMAL(12,2) NOT NULL,"payload" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Payment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Session" ("id" TEXT NOT NULL,"adminId" TEXT NOT NULL,"tokenHash" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"revokedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PaymentEvent" ("id" TEXT NOT NULL,"paymentId" TEXT NOT NULL,"externalEventId" TEXT,"eventType" TEXT NOT NULL,"payload" JSONB,"processedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PaymentEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DeliveryQuote" ("id" TEXT NOT NULL,"productId" TEXT NOT NULL,"quantity" INTEGER NOT NULL,"cityCode" INTEGER NOT NULL,"cityName" TEXT NOT NULL,"deliveryType" "DeliveryType" NOT NULL,"pointCode" TEXT,"pointName" TEXT,"pointAddress" TEXT,"address" TEXT,"tariffCode" INTEGER NOT NULL,"tariffName" TEXT NOT NULL,"price" DECIMAL(12,2) NOT NULL,"minDays" INTEGER,"maxDays" INTEGER,"expiresAt" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "DeliveryQuote_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL,"adminId" TEXT,"action" TEXT NOT NULL,"entity" TEXT NOT NULL,"entityId" TEXT,"before" JSONB,"after" JSONB,"ipAddress" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "AdminUser_email_key" ON "AdminUser"("email");
CREATE UNIQUE INDEX "Product_slug_key" ON "Product"("slug");
CREATE INDEX "Product_category_isActive_sortOrder_idx" ON "Product"("category","isActive","sortOrder");
CREATE INDEX "Review_isVisible_showOnHomepage_sortOrder_idx" ON "Review"("isVisible","showOnHomepage","sortOrder");
CREATE INDEX "FaqItem_isVisible_sortOrder_idx" ON "FaqItem"("isVisible","sortOrder");
CREATE UNIQUE INDEX "ContentBlock_key_key" ON "ContentBlock"("key");
CREATE INDEX "ContentBlock_section_isVisible_sortOrder_idx" ON "ContentBlock"("section","isVisible","sortOrder");
CREATE UNIQUE INDEX "SiteSetting_key_key" ON "SiteSetting"("key");
CREATE UNIQUE INDEX "Media_fileName_key" ON "Media"("fileName");
CREATE UNIQUE INDEX "Order_number_key" ON "Order"("number");
CREATE INDEX "Order_status_createdAt_idx" ON "Order"("status","createdAt");
CREATE INDEX "Order_email_idx" ON "Order"("email");
CREATE INDEX "Order_phone_idx" ON "Order"("phone");
CREATE INDEX "OrderItem_orderId_idx" ON "OrderItem"("orderId");
CREATE INDEX "OrderItem_productId_idx" ON "OrderItem"("productId");
CREATE UNIQUE INDEX "Payment_invoiceId_key" ON "Payment"("invoiceId");
CREATE UNIQUE INDEX "Payment_idempotencyKey_key" ON "Payment"("idempotencyKey");
CREATE INDEX "Payment_orderId_status_idx" ON "Payment"("orderId","status");
CREATE UNIQUE INDEX "Payment_provider_providerPaymentId_key" ON "Payment"("provider","providerPaymentId");
CREATE UNIQUE INDEX "Session_tokenHash_key" ON "Session"("tokenHash");
CREATE INDEX "Session_adminId_expiresAt_idx" ON "Session"("adminId","expiresAt");
CREATE INDEX "PaymentEvent_paymentId_processedAt_idx" ON "PaymentEvent"("paymentId","processedAt");
CREATE UNIQUE INDEX "PaymentEvent_paymentId_externalEventId_key" ON "PaymentEvent"("paymentId","externalEventId");
CREATE INDEX "DeliveryQuote_expiresAt_idx" ON "DeliveryQuote"("expiresAt");
CREATE INDEX "DeliveryQuote_productId_idx" ON "DeliveryQuote"("productId");
CREATE INDEX "AuditLog_entity_entityId_idx" ON "AuditLog"("entity","entityId");
CREATE INDEX "AuditLog_adminId_createdAt_idx" ON "AuditLog"("adminId","createdAt");

ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "AdminUser"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PaymentEvent" ADD CONSTRAINT "PaymentEvent_paymentId_fkey" FOREIGN KEY ("paymentId") REFERENCES "Payment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;
